### ISSUE TITLE
Memory leaks in development mode with play 2.3.4

### ISSUE THREAD

**Issue by pycloux** [playframework/playframework#3799]
Hi anybody,

We have some issues with the play development mode (no issues in production mode). Basically we are experiencing "out of memory" errors after a limited number of application reloads.

I have performed various detailed analysis using heap dumps, jconsole, hat and MAT and it appears clearly that something is being accumulated after each reload.
Basically there is one new instance of play.PlayRun$$anonfun$9$$anon$1 each time we reload.
And this one retains a lot of things.

Analysis from MAT based on a heap dump:
4 instances of "play.PlayRun$$anonfun$9$$anon$1", loaded by "sbt.PluginManagement$PluginClassLoader @ 0x7006893f0" occupy 19,890,552 (20.46%) bytes.
Biggest instances:
    play.PlayRun$$anonfun$9$$anon$1 @ 0x70396ca28 - 6,113,488 (6.29%) bytes.
    play.PlayRun$$anonfun$9$$anon$1 @ 0x703047b00 - 6,055,136 (6.23%) bytes.
    play.PlayRun$$anonfun$9$$anon$1 @ 0x704280e58 - 5,982,264 (6.15%) bytes.
    play.PlayRun$$anonfun$9$$anon$1 @ 0x704df6a00 - 1,739,664 (1.79%) bytes. 

NB: The heap dump was done after I have done a Crtl+D so the application was not running.

I obviously increased the memory allocated to the JVM but that's really not a smart solution. I can have one or two additional iterations before crash.
Any idea.

**Comment by benmccann** [comment]
Can you upgrade to Play 2.3.7 and see if the problem persists?

**Comment by richdougherty** [comment]
Sometimes threads created by your application, if they're not stopped on
application shutdown, can keep a reference to their classloader. It's worth
getting a thread dump after each reload to see if any threads are staying
around.

**Comment by pycloux** [comment]
Thanks Rich,

I performed some checks on the threads.
I found indeed one issue related to the MySQL driver which I am able to solve with AbandonedConnectionCleanupThread.shutdown().

Yet there is still one thread which is kept.
A TimerThread associated with the class  play.PlayRun$$anonfun$10$$anon$2.
After each reload I got one new thread added.
I tried to find the "PlayRun" class but was not able to find it in the source code (either in the scala sources or java sources).
Any idea ?

I'll check as suggested by Ben to run Play 2.3.7 and see if the issue is still there.

Regards,

PYC

**Comment by richdougherty** [comment]
I think a TimerThread is meant to shut down automatically once all of its Timers have finished. I've seen a TimerThread hanging around in Play before. It was caused by Ehcache setting up a Timer to phone home every day. But that should be disabled in the Ehcache configuration now. If your app has its own Ehcache configuration then it might have overridden the default configuration that disables the Ehcache Timer..

The easiest way to work out the cause is probably to attach a breakpoint to Timer/TimerThread creation so you can see what part of Play or your app is using a Timer.

**Comment by pycloux** [comment]
Hi Rich,

 

Good idea (the breakpoint).

I have no specific EHCache implementation, I am using the default one from Play.

I’ll keep you updated with this.

NB: I think it could be good to have, as part of the Play documentation, something about “common” memory issues with the dev or test mode.

 

 

Regards,

 

PYC

 

---------------------------

Pierre-Yves Cloux

Mail : pycloux@yahoo.fr

Mobile : +41 76 615 16 72

**Comment by pycloux** [comment]
So I found the Thread (a bug in Ebean certainly which is fixed in the new version, see https://github.com/ebean-orm/avaje-ebeanorm/issues/229) but unfortunatly this is not the main issue.
So the issue is not related to a thread which remains active.

This is something else...

PermGen still increasing and same accumulation of play.PlayRun$$anonfun$9$$anon$1.
So back to the initial issue.

**Comment by mingchuno** [comment]
I have got similar problem too in 2.3.7

**Comment by richdougherty** [comment]
@mingchuno, can you explain more about the problem you see? We're still not sure about what's causing the memory leak so any extra information would be useful. You may even have a different kind of memory leak.

**Comment by mingchuno** [comment]
@richdougherty Yes, I'll post the stack trace when i see it next time

**Comment by richdougherty** [comment]
Thanks for offering to send more information. To be helpful, you'll need to
post more than just the stack trace. The stack trace just tells us an error
had occurred bit it doesn't give us enough information to say why. For an
example of useful information see all the great analysis above about heap
dumps, thread dumps, breakpoints, etc.

**Comment by pycloux** [comment]
Hi Rich,

I created an empty play 2.3.7 project to have the test and the issue is there also.
Here is the procedure:
1) create a new project
2) launch activator and perform a sequence of "run" and "Ctrl+D"
3) then launch the jconsole and do a thread dump

Looking at the dump using a tool such as MAT you'll notice one instance of play.PlayRun$$anonfun$9$$anon$1 per stop/start.
I can't attach the heapdump since it's a bit heavy but it should be easy to perform the procedure described above.

Regards,

PYC

**Comment by richdougherty** [comment]
Thanks for isolating the issue to an empty project. I'll look into it.

**Comment by mingchuno** [comment]
Here is my stack trace:

```
[info] Compiling 1 Scala source to /home/mcor/dev/dc-eventsys-play/target/scala-2.11/classes...
sbt appears to be exiting abnormally.
  The log file for this session is at /tmp/sbt8992114562915536491.log
java.lang.OutOfMemoryError: Metaspace
	at sbt.ConsoleLogger.trace(ConsoleLogger.scala:143)
	at sbt.AbstractLogger.log(Logger.scala:32)
	at sbt.MultiLogger$$anonfun$dispatch$1.apply(MultiLogger.scala:40)
	at sbt.MultiLogger$$anonfun$dispatch$1.apply(MultiLogger.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at sbt.MultiLogger.dispatch(MultiLogger.scala:38)
	at sbt.MultiLogger.trace(MultiLogger.scala:30)
	at sbt.State$.logFullException(State.scala:249)
	at sbt.State$.handleException(State.scala:243)
	at sbt.State$$anon$1.handleError(State.scala:201)
	at sbt.MainLoop$.handleException(MainLoop.scala:108)
	at sbt.MainLoop$.next(MainLoop.scala:104)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
Error during sbt execution: java.lang.OutOfMemoryError: Metaspace
```

I am not using any IDE, how do I get the heap dump or MAT things like that???

**Comment by richdougherty** [comment]
Here are some instructions for getting a heap dump:
http://five.agency/java-heap-dump/. Once you have a tool you can analyse
it. @pycloux is using MAT <https://eclipse.org/mat/>. I use YourKit.
Another free tool is VisualVM. Just Google for "java heap dump analyzer"
and pick a tool that suits you.

What you want to do is capture two heap dumps. The first heap dump should
be before executing the *run* command to get an example of the normal
objects in the heap. Once you've got the first heap dump, *run* the app and
optionally reload the app *n* times. Exit the *run* command and capture
another heap dump immediately after.

The run command should have cleaned up after itself. If there are lots of
new objects in the second heap dump compared to the first heap dump then
the run command is probably leaking memory or threads. @pycloux found a
problem: "one instance of play.PlayRun$$anonfun$9$$anon$1 per stop/start".

**Comment by kirked** [comment]
To note, the OutOfMemoryError (Metaspace) also occurs in a Play/Scala project run under SBT in dev mode (not using Activator).

**Comment by jroper** [comment]
This only happens when restarting dev mode.  There are known issues there (including a thread leak in Guice that is apparently fixed in Guice 4).  During a single run of `run`, I don't see it happening, and that's where it really matters.  So I'm unassigning this from the 2.4 milestone, because solving leaks between executions of `run` would be nice but is in no way a priority to fix before we release Play 2.4.

**Comment by neurozen** [comment]
I'm not sure if this is related though when I moved form 2.3.7 to 2.3.9 I have a problem where on a reload I cannot connect to the app on localhost:9000 (via browser) and I get the following exception (if I wait for 5 minutes)

[info] ! Internal server error, for (GET) [/] ->
[info] 
[info] java.util.concurrent.TimeoutException: Futures timed out after [300000 milliseconds]
[info]  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[scala-library-2.11.1.jar:na]

This has only app read after I just migrated from Play 2.3.7 to 2.3.9.  I am developing in IntelliJ on a project created originally in activator 2.3.9 (with sources imported in). First run in IntelliJ all is ok, after that subsequent runs result in issue.

A network socket is up, but that's about it :+1: 
minibyte:~ neurozen$ netstat -an | grep -i 9000
tcp4       0      0  127.0.0.1.9000         127.0.0.1.49853        ESTABLISHED
tcp4       0      0  127.0.0.1.49853        127.0.0.1.9000         ESTABLISHED
tcp46      0      0  *.9000                 *.*                    LISTEN   

Any thoughts to whether this attributed to MemoryLeak issues  James and others are mentioning.  It is 100% repeatable for me.

**Comment by richdougherty** [comment]
@neurozen, that could be related, but I'd say probably not. It could be another bug though. Are you able to create a small app to replicate it?

**Comment by richdougherty** [comment]
Tagging as 2.4 because I'd like to check this is fine as part of our bug cleanup for the 2.4 release. Any fix that's not too complicated would be backported.

**Comment by jroper** [comment]
The issue is most likely an sbt-server issue, I think that timeout is waiting for sbt server to come up or something, it seems to happen for some users. There's a way to make it not use sbt server, not sure how though. Also, you can simply not use activator ui, just use activator run.

**Comment by benmccann** [comment]
@jroper do you have any details regarding the thread leak in guice 3? the guice devs are asking about it: https://groups.google.com/forum/#!topic/google-guice/14i5Q3utwGI

**Comment by neurozen** [comment]
@richdougherty @jroper Sorry for late reply.  My particular issue with hanging does seem be with sbt.  All is fine when I set `fork in run := false` in *build.sbt*.  Are you still interested in a small app that re-creates the issue?

**Comment by benmccann** [comment]
We might be able to get Guice 4.0 in time for Play 2.4. They said they're close to cutting a release. I'm sending them PRs now to help prepare for a release

See https://groups.google.com/d/msg/google-guice/14i5Q3utwGI/JGRCZbGkgSgJ

**Comment by richdougherty** [comment]
@benmccann, it would be awesome if they can get a release out.

**Comment by benmccann** [comment]
Guice 4.0 has been released :-)  https://github.com/playframework/playframework/pull/4321

**Comment by marcospereira** [comment]
I could reproduce this issue with Play 2.4.0-RC1 (which was not using Guice 4.0) following the steps described by @pycloux. Every cycle of run/ctrl-d leaked a Guice thread (a Finalizer). Apart of that, the thread number was quite stable.

But I can't reproduce it with the current master (which has Guice 4.0). Even after a lot of run/ctrl-d, the number of threads were stable. So, I think we can close this issue.

@jroper, @benmccann, @richdougherty WDYT?

**Comment by jroper** [comment]
That's great to know! I think we can close it.

**Comment by richdougherty** [comment]
:)

**Comment by LubomirVarga** [comment]
Adding "-XX:MaxMetaspaceSize=512m" to java opts will help in development environment.

**Comment by shkhln** [comment]
Just a polite reminder that this issue, at least originally, is _not_ about _thread_ leaks at all. The _memory_ leak involving play.runsupport.Reloader with it's friends is perfectly reproducible in 2.4, 2.5 and current master branch. Please reopen.

**Comment by benmccann** [comment]
Thread leaks are the cause of the memory leaks. And yes, they are still happening :-(  There is another open issue to track: https://github.com/playframework/playframework/issues/4649

**Comment by shkhln** [comment]
Thank you, but I like this one more. The other issue is too general, there is quit a big risk of people getting sidetracked again.

**Comment by shkhln** [comment]
Need to mention that this memory leak is not reproducible with PlayAkkaHttpServer, so I think it is somehow Netty related.

**Comment by richdougherty** [comment]
@shkhln, it's quite easy for memory/thread/resource leaks to creep into Play. To get a leak all we need to do is have one Play dependency that starts a thread or stores a value in a static variable.

If you're seeing leaks what would be really helpful for debugging would be some sort of "diff" that shows threads that aren't shut down or memory that isn't initialised. If you want to help with diagnosing the problem I can probably get you a license for [YourKit](https://www.yourkit.com/) (they often sponsor us with licenses). It's not really too hard to get the information, but it does take quite a bit of time and care to find the needle (leak) in the haystack (heap/thread dumps).

We can keep this issue open if you like, but if you do want to start tracking down specific leaks then it can be helpful to track them separately so we can fix them separately. Sometimes there are 3 or 4 leaks!

**Comment by shkhln** [comment]
Yes, that takes a lot of time. For that Netty issue see https://github.com/playframework/playframework/issues/5144#issuecomment-243692348.

**Comment by shkhln** [comment]
I've only relatively recently found I can use --fontsize argument to be able to see VisualVM on a high-dpi display (with Java 8), which means I can play metaspace whack-a-mole game again: https://gist.github.com/shkhln/b8ee1f6d2930da11f2d2de262fafa987.

**Comment by marcospereira** [comment]
Duplicate of #4649.
