### ISSUE TITLE
Read play.editor from config

### ISSUE THREAD

**Issue by mariussoutier** [playframework/playframework#3892]
Currently you have to pass `Dplay.editor="..."` on the console. In a team setting it would be nicer if it was read from everybody's dev config.

**Comment by nafg** [comment]
You can put it in a .sbtopts file (though the wisdom of committing that to
version control is questionable...)

**Comment by jroper** [comment]
This was fixed in #3444.

**Comment by mariussoutier** [comment]
Was this ever merged into a release? Still doesn't seem to work in 2.4.2...

**Comment by wsargent** [comment]
Confirmed -- in application.conf:

```
play.editor="http://localhost:63342/api/file/?file=%s&line=%s"
```

Go to https://chrome.google.com/webstore/detail/play-framework-tools/dchhggpgbommpcjpogaploblnpldbmen?hl=en-US to download chrome's play framework tools:

Right click on the Playframework Tools button, then click "Options" from the menu list.

Where it says: "For Open in editor URL (use $file and $line as placeholders for the absolute file path and line number):" 

Enter `http://localhost:63342/api/file/?file=$file&line=$line`

Then hit the save button.  Then, in an already running Play application, change some source code to break.  You will see the URL with hyperlink.  Clicking on the hyperlink with Intellij IDEA 2016.1 will cause focus to shift to IntelliJ on that line.

**Comment by mariussoutier** [comment]
I'm confused now, the Chrome extension has nothing to do with `play.editor`. The point of `play.editor`, to me, was that it didn't require and extensions and would work in any browser.

**Comment by nafg** [comment]
https://github.com/playframework/playframework/commit/6d9311703f695574d005fffc72caa210aa8a1c16
says
it's in


   - master <https://github.com/playframework/playframework>
   - (#3444 <https://github.com/playframework/playframework/pull/3444>)



   - 2.5.1
   <https://github.com/playframework/playframework/releases/tag/2.5.1>
   -
   - 2.5.0
   <https://github.com/playframework/playframework/releases/tag/2.5.0>
   - 2.5.0-RC2
   <https://github.com/playframework/playframework/releases/tag/2.5.0-RC2>
   - 2.5.0-RC1
   <https://github.com/playframework/playframework/releases/tag/2.5.0-RC1>
   - 2.5.0-M2
   <https://github.com/playframework/playframework/releases/tag/2.5.0-M2>
   - 2.5.0-M1
   <https://github.com/playframework/playframework/releases/tag/2.5.0-M1>
   - 2.4.6
   <https://github.com/playframework/playframework/releases/tag/2.4.6>
   - 2.4.5
   <https://github.com/playframework/playframework/releases/tag/2.4.5>
   - 2.4.4
   <https://github.com/playframework/playframework/releases/tag/2.4.4>
   - 2.4.3
   <https://github.com/playframework/playframework/releases/tag/2.4.3>
   - 2.4.2
   <https://github.com/playframework/playframework/releases/tag/2.4.2>
   - 2.4.1
   <https://github.com/playframework/playframework/releases/tag/2.4.1>
   - 2.4.0
   <https://github.com/playframework/playframework/releases/tag/2.4.0>
   - 2.4.0-RC5
   <https://github.com/playframework/playframework/releases/tag/2.4.0-RC5>
   - 2.4.0-RC4
   <https://github.com/playframework/playframework/releases/tag/2.4.0-RC4>
   - 2.4.0-RC3
   <https://github.com/playframework/playframework/releases/tag/2.4.0-RC3>
   - 2.4.0-RC2
   <https://github.com/playframework/playframework/releases/tag/2.4.0-RC2>
   - 2.4.0-RC1
   <https://github.com/playframework/playframework/releases/tag/2.4.0-RC1>
   - 2.4.0-M3
   <https://github.com/playframework/playframework/releases/tag/2.4.0-M3>
   - 2.4.0-M2
   <https://github.com/playframework/playframework/releases/tag/2.4.0-M2>

**Comment by nafg** [comment]
On Thu, Apr 7, 2016 at 8:43 PM Will Sargent <notifications@github.com>
wrote:

> Confirmed -- in application.conf:
>
> play.editor="http://localhost:63342/api/file/?file=%s&line=%s"
>
> Go to
> https://chrome.google.com/webstore/detail/play-framework-tools/dchhggpgbommpcjpogaploblnpldbmen?hl=en-US
> to download chrome's play framework tools:
>
> Right click on the Playframework Tools button, then click "Options" from
> the menu list.
>
> Where it says: "For Open in editor URL (use $file and $line as
> placeholders for the absolute file path and line number):"
>
> Enter http://localhost:63342/api/file/?file=$file&line=$line
>
So you have to enter it in both places?!

**Comment by wsargent** [comment]
Documentation is indeed misleading -- I thought it required both ends, it's actually supposed to be either.  I can see that "play.editor" exists in configuration, but I don't see the hyperlink when set.  Will poke more at this.

**Comment by wsargent** [comment]
Okay, I see why you can't set play.editor from `application.conf`.  play.editor is only set when the application is working.

Server.scala runs through:

```
    try {
      applicationProvider.handleWebCommand(request) match {
        case Some(result) =>
          Left(Future.successful(result))
        case None =>
          applicationProvider.get match {
            case Success(application) =>
              application.requestHandler.handlerForRequest(request) match {
                case (requestHeader, handler) => Right((requestHeader, handler, application))
              }
            case Failure(e) => logExceptionAndGetResult(e)
          }
      }
    } catch {
      case e: ThreadDeath => throw e
      case e: VirtualMachineError => throw e
      case e: Throwable =>
        logExceptionAndGetResult(e)
    }
```

Then it goes through to `logExceptionAndGetResult`:

```
    def logExceptionAndGetResult(e: Throwable): Left[Future[Result], Nothing] = {
      Left(DefaultHttpErrorHandler.onServerError(request, e))
    }
```

But that's attached to the global singleton, because there's no application available.
 
```
object DefaultHttpErrorHandler extends DefaultHttpErrorHandler(Environment.simple(), Configuration.empty, None, None)
```

**Comment by wsargent** [comment]
I think that Configuration.empty is too harsh here: the configuration should be loaded even if nothing else is, and a failing config (i.e. bad HOCON) should realistically hose everything.  In particular, Configuration.empty doesn't load system properties, which means even -Dplay.editor won't work.

**Comment by wsargent** [comment]
@mariussoutier should be fixed in 2.5.2, give it a shot

**Comment by mariussoutier** [comment]
Works now using `-Dplay.editor`. Thank you!
