### ISSUE TITLE
[2.3.10] Compiling with "-Ywarn-unused-import" warns on Twirl templates

### ISSUE THREAD

**Issue by jawshooah** [playframework/playframework#5216]
Adding `-Ywarn-unused-import` and `-Xfatal-warnings` to `scalacOptions` in my build results in errors on the first line of every Twirl template:

```
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/BuildInfo.scala.html:1: Unused import
[error] @(projectName: String, projectVersion: String, buildDate: String)
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/EmailStyle.scala.html:1: Unused import
[error] <style>
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/ForgotUsernameMail.scala.html:1: Unused import
[error] @(userName: String, firstName: String, link: String)
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/MailFooter.scala.html:1: Unused import
[error] <p>Thank you, <br>
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/MailHeader.scala.html:1: Unused import
[error] <table class="header-container">
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/PasswordResetConfirmationMail.scala.html:1: Unused import
[error] @(firstName: String, changedDateTime: String)
[error] ^
[error] /Users/joshuahagins/dev/sentrana/samba/samba-core/app-shell/app/views/emails/PasswordResetMail.scala.html:1: Unused import
[error] @(firstName: String, link: String, securityCode: String, timeout: Int)
[error] ^
```

**Comment by jankeesvanandel** [comment]
I have the same issue. It complains both in my Play templates as well as in my routes files.

For example:
```
GET        /bla          @path.to.Class.method()
```

Gives the following error:
```
[error] .../bla.routes:8: Unused import
[error] GET        /bla                          @path.to.Class.method()
```

On first sight it seems to be related to the @ symbol...?

**Comment by Pyppe** [comment]
Any news regarding this? We're annoyed by this as well.

**Comment by mkurz** [comment]
Warnings coming from the routes file should be fixed in 2.3.9 already via #4114

For Twirl there is a open issue: https://github.com/playframework/twirl/issues/105

@Pyppe Which Play version are you using?

**Comment by Pyppe** [comment]
@mkurz Thanks for the link to a more relevant issue. We're not actually even using using play framework (just the twirl templates). Ended up here googling the twirl import issue.

**Comment by cretz** [comment]
@mkurz - The routes file issue still occurs with at least 2.4 with unused import checks on.

**Comment by marcospereira** [comment]
@cretz the fix for routes was made at #6284. It was not backported to 2.5.x yet, but I think it should.

**Comment by marcospereira** [comment]
@cretz #6284 was backported to 2.5.x at #6407 thanks to @mkurz.

I'm closing this since it should be addressed at playframework/twirl#105.
