### ISSUE TITLE
Cleaner error messages in case json body parsing fails

### ISSUE THREAD

**Issue by francisdb** [playframework/playframework#6672]
Currently (2.5.x) for

```scala
Json.parse("test")
```
you get this

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'test': was expecting 'null', 'true', 'false' or NaN
[error]     at [Source: test; line: 1, column: 9]
```

But when the json body parsers fail you get an error like this

```
Invalid Json: Unrecognized token 'test': was expecting 'null', 'true', 'false' or NaN
[error]     at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@7ed0dd6d; line: 1, column: 6]
```

This whole `ByteArrayIterator#toString()` output should not be visible to the consumer of the api.

One way to avoid this is to wrap the iterator with something that has a cleaner `toString()`

An other way this can be fixed is by adding a specific catch for `JsonParseException` and using it's `getOriginalMessage()` accessor which does not contain location information. If needed you can call `getLocation()` to append the line and column.

As a workaround I tried to have a go at fixing this by copy pasting and modifying some code from `ContentTypes.scala`. But as a lot of the related code is private I ended up duplicating a LOT of the existing code.

**Comment by wsargent** [comment]
Is `Json.validate` not doing what you want?

**Comment by francisdb** [comment]
And how would that help me with `BodyParsers.parse.json*`? Validation happens after parsing?

**Comment by francisdb** [comment]
Also this is somewhat related to #3893

**Comment by francisdb** [comment]
@wsargent your solution yields the same problem

```html
[error]        <body>
[error]            <h1>Bad Request</h1>
[error]
[error]            <p id="detail">
[error]                For request 'GET /' [Invalid Json: Unexpected end-of-input: expected close marker for Object (start marker at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@40b7d060; line: 1, column: 1])
[error]     at [Source: akka.util.ByteIterator$ByteArrayIterator$$anon$1@40b7d060; line: 1, column: 3]]
[error]            </p>
[error]
[error]        </body>
```

**Comment by schmitch** [comment]
actually this is definitly a duplicate of #3893

**Comment by francisdb** [comment]
@schmitch however this is fixed, it should handle both the json parsing and the json ast validation (reads/format)
Currently it is easy to modify the validation errors in a custom way but not the parsing errors.

**Comment by schmitch** [comment]
it's still easy to modify them. create your own body parser is not really a hard thing to do.
and actually they are not fixed.

**Comment by francisdb** [comment]
It's not easy, you have to copy paste quite some of the private methods in ContentTypes.scala to just patch the parsing error and keeping everything else as is

**Comment by bharal** [comment]
I sent data up with:

$.ajax({
		url: r.url, 
		type: r.type, 
		contentType: "application/json",		
		data: { buildingId:$(fnThis).attr("data-href") },
		success: function(response){
		},
		error: function(){ }
	});

amazingly, the response was that it isn't valid JSON! This is valid JSON - but for some reason play wanted me to convert it to a string? (So data: blahblah -> data: JSON.stringify(blahBlah)

Needs to be a much cleaner error message just saying to wrap it as a string! Error messages should be useful, not just random gibberish words!

**Comment by richdougherty** [comment]
By the way #6171 captures the discussion about improving error handling generally.

**Comment by dspasojevic** [comment]
We were pinged no this issue in a security audit because they view this as an implementation detail leaking to the consumer.

Does anyone know if there a better way of suppressing these particular pieces of information copy-pastaing or regexing it out?

**Comment by dspasojevic** [comment]
For future readers, our solution (as per @francisdb's suggestion) ended up looking like:

```scala
class ObsfucatingJsonBodyParser @Inject() (val config: ParserConfiguration, val errorHandler: HttpErrorHandler, val materializer: Materializer, val temporaryFileCreator: Files.TemporaryFileCreator)
    extends PlayBodyParsers {

  // Copied.
  override def json(maxLength: Long): BodyParser[JsValue] = when(
    _.contentType.exists(m => m.equalsIgnoreCase("text/json") || m.equalsIgnoreCase("application/json")),
    tolerantJson(maxLength),
    createBadResult("Expecting text/json or application/json body", Status.UNSUPPORTED_MEDIA_TYPE)
  )

  // Copied then modified
  override def tolerantJson(maxLength: Long): BodyParser[JsValue] =
    tolerantBodyParser[JsValue]("json", maxLength, "Invalid Json") { (_, bytes) =>
      try Json.parse(bytes.iterator.asInputStream)
      catch {
        case e: JsonParseException =>
          throw new Exception(e.getOriginalMessage()) // Modified here.
      }
    }

  // Copied
  override def json: BodyParser[JsValue] = json(DefaultMaxTextLength)
}
```

This has all the future maintenance problems that you'd expect, but seemed less bad that other solutions (pre-parsing the possible JSON input, regexing the value out of the location information in an error handler, etc).

**Comment by gmethvin** [comment]
Given that this seems specific to Jackson, is there any opposition to changing the default body parsers to special-case Jackson exceptions and use `getOriginalMessage`? Or at least do that for production applications?
