### ISSUE TITLE
Logger configuration is being ignored by play

### ISSUE THREAD

**Issue by daveseco7** [playframework/playframework#7084]
Hi,

Me and my team are migrating an existing project from Play **2.3.X** to Play version **2.5.10**, we're having a bit of trouble regarding the logger feature. As it stands, our logback configuration (`logback.xml`) is not been used by the play framework. We're using **gradle** as our building tool and even try to use the flags ` -Dlogger.resource` and `-Dlogger.file` to ensure the configuration file is being loaded. I can assure you that the full content of the conf folder is beeing loaded to the classpath, since we're using other files that are located in this folder.

This problem only occurs if we start the project in **DEV** mode, in **PROD** mode all runs smoothly and all logger configurations are used as expected.

Is there any workaround or configuration missing from the play documentation website? 

### Operating System (Ubuntu 15.10 /Windows 10)
Linux apoc 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### JDK (Oracle 1.8.0_111)
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**Comment by mkurz** [comment]
Hmm... Maybe somehow related to #6039 (which was fixed in 2.5.11)
Please upgrade to latest version 2.5.13 and see if it's working.

**Comment by daveseco7** [comment]
I have upgraded to play version 2.5.13 but the problem still persists. I had already found the mentioned issue while doing some research, but I think it is a different use case. In the linked issue, the user was trying to load a LoggerConfigurator, in my use case, I'm only trying to specify the level of logging.

**Comment by wsargent** [comment]
Not heard of this issue before -- https://www.lucidchart.com/techblog/2017/02/22/upgrading-play-framework-2-3-play-2-5/ works fine, could be related to gradle?

**Comment by wsargent** [comment]
Also, have you seen https://docs.gradle.org/3.4.1/userguide/play_plugin.html and tried it with sbt?

**Comment by daveseco7** [comment]
Yes, I have searched and read the gradle documentation. I'm not sure whether it's gradle related or play related. We're migrating multiple projects with a different` build.gradle` logic and in every one, logger configuration is being ignored which did not happen before. I have not yet tested with sbt since all of out projects are gradle based.

Note: I have updated to gradle 2.4.1 but the problem still persists.

**Comment by wsargent** [comment]
The LogbackLoggerConfigurator should be called by Gradle, but if it isn't you can call it manually:

https://www.playframework.com/documentation/2.5.x/SettingsLogger#Using-a-custom-application-loader

I would also look at the source code:

https://github.com/playframework/playframework/blob/master/framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala

and the log4j2 example: https://github.com/playframework/play-scala-log4j2-example/

**Comment by wsargent** [comment]
Since this isn't something we can reproduce and seems to only affect your projects, it sounds like it may not be a Play bug (or at least, not one we can investigate).  I'll close it for now, and if you have any extra information we can reopen it.

**Comment by arjunchhabra** [comment]
I am encountering the same issue and am also using Gradle for my build management tool. I am calling the Logging Configurator directly in my custom ApplicationLoader class.
