### ISSUE TITLE
classloader leak in run command

### ISSUE THREAD

**Issue by ornicar** [playframework/playframework#9935]
`kamon.Kamon.counter("foo")` causes a classloader leak when using `run`. This causes OOM after a few runs, depending on the application size, and makes the dev workflow unusable.

Here's a minimal project with instructions to reproduce the issue: https://github.com/ornicar/play-cdi-leak/tree/kamon

My setup:
- Linux 5.4.2
- openjdk version "13.0.1" 2019-10-15
- scala 2.13.1
- playframework 2.8.0
- sbt 1.3.5

Same issue on Kamon side: https://github.com/kamon-io/Kamon/issues/629

**Comment by ornicar** [comment]
I observed the same leak, this time with lettuce.

Demo project: https://github.com/ornicar/play-cdi-leak/#playframework-dev-workflow-classloader-leaks

It seems that when a scala `object` has a reference to a resource,
it prevents the resource from being released after a `run`,
and causes the entire application instances and classes to remain loaded forever.

It's arguably not great to have a reference a resource in an `object`,
but I see many reasons why it would happen, and third party libraries like Kamon apparently do it.

**Comment by ornicar** [comment]
Maybe I'm just supposed to clear that state manually with `lifecycle.addStopHook`? It wasn't necessary with play 2.4.

**Comment by ornicar** [comment]
Kamon and sbt 0.12.8: same leak. Reproduce with https://github.com/ornicar/play-cdi-leak/tree/kamon-sbt-0.12.8

**Comment by ornicar** [comment]
Kamon and sbt 0.13.18: same leak. Reproduce with https://github.com/ornicar/play-cdi-leak/tree/kamon-sbt-0.13.18

**Comment by ornicar** [comment]
Kamon, play 2.7.4, sbt 1.3.2: same leak. https://github.com/ornicar/play-cdi-leak/tree/kamon-play-2.7

**Comment by ornicar** [comment]
play 2.6.25: same leak. I'm very confused now.

- Linux 5.4.2
- openjdk 11.0.5
- scala 2.12.10
- playframework 2.6.25
- sbt 1.2.8

Again, all application instances and classes remain loaded in memory forever. How can anyone use `run` in these conditions? Is it just me? Please try and reproduce: https://github.com/ornicar/play-cdi-leak/tree/kamon-play-2.6

**Comment by ornicar** [comment]
Using caffeine's system scheduler also causes the leak. https://github.com/ornicar/lila/commit/356828b67410a170c900ccb392b92300be63036b#diff-2c97c4926d21143282d73716e78e6dbdR10-R11

**Comment by SethTisue** [comment]
there's discussion on this, and at least a partial resolution, at https://github.com/ornicar/play-cdi-leak/pull/1, thanks to @wsargent

**Comment by marcospereira** [comment]
Hey @ornicar, I'm not sure if there is something we can do on our side related to that. As @wsargent explained, if a resource has some sort of initialization that needs to be undone, like the Kamon agent apparently does, then we already provide the APIs to make that happen (although I'm not sure Kamon has something like `shutdown`, `close`, etc.).

This is what I'm getting after commenting out the `kamon.Kamon.counter` line:

<img width="1634" alt="Screen Shot 2020-01-29 at 2 39 01 AM" src="https://user-images.githubusercontent.com/4576/73368469-04618080-427f-11ea-9b7d-42e49dd1e0a4.png">

As you can see, GC is doing what is suppose to do and unloading classes from metaspace.

---

Still, there is a lot of changes involved here: sbt, Play, and Kamon (which I suppose you had to update when moving to Play 2.8.0, right?). I will keep this open since you are still doing some investigation on your side though.

**Comment by marcospereira** [comment]
A possible workaround is to have a flag to activate Kamon in dev mode, maybe? So that you can run something like `sbt -Dkamon=true` and check for this property in the application loader. But I'm not sure how this impacts other places where Kamon API is used.

**Comment by shkhln** [comment]
I'm afraid the only working solution there involves resetting static fields in third party code through reflection. See [classloader-leak-prevention](https://github.com/mjiderhamn/classloader-leak-prevention) for an example of this approach.

Personally, I'm using the code from this [gist](https://gist.github.com/shkhln/b8ee1f6d2930da11f2d2de262fafa987) for Play 2.6 and reloads _within_ a single run. Classloader leaks with multiple runs are a lost cause in my opinion.

**Comment by marcospereira** [comment]
Hey @shkhln,

Thank you for pointing that out. It looks like some of those clean ups in the gist we need to do out-of-the-box (the one for `DefaultTemporaryFileCreator`, Jackson, and Logback at least).

Do you want to submit a PR for that?

**Comment by shkhln** [comment]
The `DefaultTemporaryFileCreator` fix does not apply to the subsequent Play versions, don't bother with that one.

> Do you want to submit a PR for that?

Obviously not. Most of these fixes (by necessity) completely ignore public APIs.

**Comment by mkurz** [comment]
This has been fixed by kamon by introducing a `stop()` method in kamon 2.1.11.
That means you can now call
```scala
    appLifecycle.addStopHook { () =>
      Kamon.stop()
    }
```
to stop kamon and free its resources.

See https://github.com/kamon-io/Kamon/issues/629#issuecomment-771067136 and https://github.com/kamon-io/Kamon/pull/804 for mor info.

There is nothing to fix in Play here.

**Comment by mkurz** [comment]
@jtjeferreira Since you did some work regarding memory leaks, do you think adding parts of the gist into Play core makes sense? See https://github.com/playframework/playframework/issues/9935#issuecomment-585495107

**Comment by jtjeferreira** [comment]
> @jtjeferreira Since you did some work regarding memory leaks, do you think adding parts of the gist into Play core makes sense? See [#9935 (comment)](https://github.com/playframework/playframework/issues/9935#issuecomment-585495107)

In my work project I still have something similar to that gist for:
* DefaultTemporaryFileCreator leak, but this was already fixed in #10498
* Jackson TypeFactory cache
* Logback ContextClassLoader

I think it would make sense to fix the last 2 in Play core...

**Comment by mkurz** [comment]
@jtjeferreira Do you want to provide a pull request?

**Comment by jtjeferreira** [comment]
> @jtjeferreira Do you want to provide a pull request?

I am a bit busy this week. Will try to go for it in the weekend

**Comment by shkhln** [comment]
Hmm… Can't remember why I thought the DefaultTemporaryFileCreator leak was fixed in 2.7. Anyway, I updated the gist for Play 2.8.

**Comment by jtjeferreira** [comment]
> > @jtjeferreira Since you did some work regarding memory leaks, do you think adding parts of the gist into Play core makes sense? See [#9935 (comment)](https://github.com/playframework/playframework/issues/9935#issuecomment-585495107)
> 
> In my work project I still have something similar to that gist for:
> 
>     * DefaultTemporaryFileCreator leak, but this was already fixed in #10498
> 
>     * Jackson TypeFactory cache
> 
>     * Logback ContextClassLoader
> 
> 
> I think it would make sense to fix the last 2 in Play core...

I commented the fixes in my work project for Jackson and Logback, and could not reproduce any leaks, so maybe things are fixed :shrug: ?
